# Project information
site_name: DiscordSRV Wiki
site_url: https://docs.discordsrv.com/
site_author: granny
site_description: >-
  The official documentation for DiscordSRV.
  The most powerful, configurable, open-source Discord bridge plugin out there.
nav:
  - Home: index.md
  - Frequently Asked Questions: faq.md
  - Installation:
    - installation/index.md
    - Initial Setup: installation/initial-setup.md
    - Sync Setup: installation/sync-setup.md
    - Voice Setup: installation/voice-setup.md
    - Link to Join Setup: installation/link-to-join-setup.md
  - Configs:
    - alerts.yml: alerts.md
    - config.yml: config.md
    - linking.yml: linking.md
    - messages.yml: messages.md
    - synchronization.yml: synchronization.md
    - voice.yml: voice.md
  - Commands: commands.md
  - Permissions: permissions.md
  - Hooked plugin features:
    - LuckPerms Contexts: lp-contexts.md
    - PlaceholderAPI Placeholders: papi-placeholders.md
  - Troubleshooting:
    - Report a bug: https://github.com/DiscordSRV/DiscordSRV/issues
    - Request a feature: https://github.com/DiscordSRV/DiscordSRV/issues
    - Ask for support: https://discordsrv.com/discord
repo_url: https://github.com/DiscordSRV/Documentation
repo_name: Documentation
edit_uri: edit/master/docs/
#extra_javascript:
#  - js/extra.js
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  favicon: images/logo.png
  logo: images/logo.png
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.instant
  palette:
    - scheme: slate
      primary: light blue
      accent: blue
plugins:
  - search
  - markdownextradata:
      jinja_options:
        comment_start_string: __CUSTOMCOMMENTSTART__
  - glightbox
  - redirects:
      redirect_maps:
        'Installation.md': 'installation/index.md'
        'PAPI-Placeholders.md': 'papi-placeholders.md'
        'LPContext.md': 'lp-contexts.md'
        'FAQ.md': 'faq.md'
        'Commands.md': 'commands.md'
        'Permissions.md': 'permissions.md'
        'installation/basic-setup.md': 'installation/initial-setup.md'
markdown_extensions:
  - pymdownx.caret
  - def_list
  - mdx_grid_tables
  - attr_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.snippets:
      base_path:
      - docs/_snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.magiclink
  - markdown.extensions.md_in_html
  - toc:
      permalink: ðŸ”—
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  project:
    version: 1.26.2
    supported_version:
      min: 1.7.9
      max: 1.20.x
  social:
    - icon: fontawesome/brands/discord
      link: http://discordsrv.com/discord
      name: DiscordSRV Discord Server
